name: untitled
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  kakao_flutter_sdk: ^1.9.5
  http: ^1.2.2
  kakao_flutter_sdk_user: ^1.9.5
  # kakaomap_webview: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.18

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#F4F4F4"
  image: assets/mbti.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true
